kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argilla-anyuid-scc
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["anyuid"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argilla-anyuid-scc
subjects:
  - kind: ServiceAccount
    name: argilla
roleRef:
  kind: Role
  name: argilla-anyuid-scc
  apiGroup: rbac.authorization.k8s.io
